### ISSUE TITLE
Duplicated gore mesh and stacking.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#179]
Patch: 4498
Server: NY8 Official
Gore meshes stack on top of each other, making them float.
Some corpses still leave duplicated gore meshes.
![20171009172912_1](https://user-images.githubusercontent.com/30121219/31350420-087bfe2c-ad1f-11e7-9fee-aedfdc2ded9a.jpg)
![20171009172920_1](https://user-images.githubusercontent.com/30121219/31350423-0aa73c34-ad1f-11e7-9737-6ca13de8d949.jpg)

**Comment by deathlyrage** [comment]
Fixed in 4505

**Comment by MarianaBoni** [comment]
Corpse stacking is still an issue on 4513
![20171013113743_1](https://user-images.githubusercontent.com/30121219/31550422-3520de68-b029-11e7-9b4b-d2633ad5f290.jpg)
