### ISSUE TITLE
Music Volume doesn't get reduced when changed in Audio Settings.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#227]
Patch: 4621
When changed the music volume on audio settings, the music doesn't change, only sounds changing it's the ambient sound playing in the background.
https://youtu.be/XHgVj1CBmWA

**Comment by deathlyrage** [comment]
Fixed

**Comment by oOCircleofLifeOo** [comment]
Tested on game version .4628 and it´s still not fixed. Can´t change the volume of it in any way.

**Comment by Punchpacket** [comment]
Confirmed as fixed in 4633, closing issue.
