### ISSUE TITLE
Eating animation still playing after corpse is gone.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#295]
Patch: 4691
Server: Hosted
After eating a corpse, if you keep pressing E, the eating animation keeps playing.
https://www.youtube.com/watch?v=ig3y4HHwmfk&feature=youtu.be

**Comment by AroraTitania** [comment]
Happens with every carnivore so far.

**Comment by deathlyrage** [comment]
Fixed in 4731

**Comment by oOCircleofLifeOo** [comment]
Still happening in .4737 (tested with "Tyrannosaur" on hosted Testmap).

**Comment by MarianaBoni** [comment]
Couldn't be tested on 37 if gore meshes weren't working. I'll test it after the gore mesh issue
