### ISSUE TITLE
Other players will see you slide eating when you finish a corpse.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#318]
Patch: 4775
Server: Dedicated server (Dev Kit) 
When player x finishes eating a corpse, player y will see them eating and sliding simultaneously. After biting, player x appears normal for player y.
https://youtu.be/kbPYFOKgFAY

**Comment by deathlyrage** [comment]
Fixed in 4779

**Comment by MarianaBoni** [comment]
As of patch 83, the issue still exists. It now stops on it's own after the animation loop is complete as seen here: https://youtu.be/Ht6Ujbwr74A
