### ISSUE TITLE
Missing moving Mods functionality.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#346]
Patch: 4837
When on the Mods Menu/UI, there's green rectangular buttons on the Enabled Mods that were used to be able to move Mods above/under each other, depending on priority.
These don't work anymore and missing their arrow symbols and sounds.
https://youtu.be/ng6klvLmHn8

**Comment by dinosauriac** [comment]
I've updated the mods menu, this should hopefully be fixed now. I can't really test it very well in-editor.

**Comment by MarianaBoni** [comment]
Patch 4840: The arrows now appear, it's still missing sounds and don't work,
The arrows also don't have a box/button on the "Disabled Mods" side.
https://youtu.be/S0qDAlnsiV8

**Comment by dinosauriac** [comment]
Were these actually functional in the old UI?

**Comment by MarianaBoni** [comment]
I just checked the old UI on public branch and it also doesn't work there.
